import type { Metadata } from "next";
import { Parkinsans, Inter} from "next/font/google";
import "@/app/styles/globals.css";
import "@/app/styles/custom.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import HeaderComponent from "@/components/layouts/HeaderComponent";
import SidebarComponent from "@/components/layouts/SidebarComponent";
import FooterComponent from "@/components/layouts/FooterComponent";
config.autoAddCss = false;
const parkinsans = Parkinsans({
  variable: "--font-parkinsans",
  subsets: ["latin"],
  fallback: ["system-ui", "arial"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  fallback: ["system-ui", "arial"]
});

export const metadata: Metadata = {
  title: "Inforisen Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${parkinsans.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SidebarComponent/>
        <HeaderComponent />
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
